[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dynaconf>=3.2.10",
    "fastapi>=0.115.12",
    "pyserial>=3.5",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.2",
]
