db_url = "sqlite:///db.sqlite"
db_echo = false

serial_port = "/dev/ttyUSB0"
serial_baudrate = 115200
serial_timeout = 1

logging_level = "INFO"

voltage_threshold = 13

cmd_max_retry = 3
cmd_max_check_retry = 10
cmd_sleep_ms = 400

token_size = 12
token_lifespan = 1

battery_voltage_threshold = 10
battery_max_temp = 40
